"""Filesystem layout for the directory repository."""

from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent
SRC_DIR = PACKAGE_DIR.parent
ROOT = SRC_DIR.parent

CONFIG_DIR = ROOT / "config"
DATA_DIR = ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
NORMALIZED_DIR = DATA_DIR / "normalized"
METADATA_DIR = DATA_DIR / "metadata"
GENERATED_DIR = ROOT / "generated"
CATEGORIES_DIR = GENERATED_DIR / "categories"
INDEXES_DIR = GENERATED_DIR / "indexes"
TEMPLATES_DIR = ROOT / "templates"
SCRIPTS_DIR = ROOT / "scripts"

UPSTREAM_JSON = RAW_DIR / "upstream.json"
PARSED_JSON = RAW_DIR / "parsed.json"
APIS_JSON = NORMALIZED_DIR / "apis.json"
DUPLICATES_JSON = NORMALIZED_DIR / "duplicates.json"
SCHEMA_JSON = METADATA_DIR / "schema.json"
CATEGORIES_JSON = METADATA_DIR / "categories.json"
STATS_JSON = METADATA_DIR / "stats.json"
LINK_HEALTH_JSON = METADATA_DIR / "link_health.json"
OVERRIDES_JSON = METADATA_DIR / "overrides.json"

SCORING_YML = CONFIG_DIR / "scoring.yml"
CATEGORIES_YML = CONFIG_DIR / "categories.yml"
USE_CASES_YML = CONFIG_DIR / "use_cases.yml"

ROOT_README = ROOT / "README.md"
CHANGELOG = ROOT / "CHANGELOG.md"
GENERATED_README = GENERATED_DIR / "README.md"
GENERATED_APIS = GENERATED_DIR / "APIs.md"

BANNER = "<!-- DO NOT EDIT: Generated by scripts/build.py -->"

UPSTREAM_README_URL = (
    "https://raw.githubusercontent.com/public-apis/public-apis/master/README.md"
)
UPSTREAM_COMMIT_URL = (
    "https://api.github.com/repos/public-apis/public-apis/commits/master"
)
UPSTREAM_REPO_URL = "https://github.com/public-apis/public-apis"
USER_AGENT = "public-apis-directory/0.1 (+https://github.com/public-apis/public-apis)"

AUTH_VALUES = ("No", "apiKey", "OAuth", "X-Mashape-Key", "User-Agent")
HTTPS_VALUES = ("Yes", "No")
CORS_VALUES = ("Yes", "No", "Unknown")
YES_NO_UNKNOWN = ("Yes", "No", "Unknown")

MIN_API_COUNT = 1000
FUZZY_NAME_THRESHOLD = 90
DEAD_FAILURE_STREAK = 3
